#!/usr/bin/env bash
# script automates the installation and configuration of an nginx web server

sudo apt-get update  -y
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sudo service nginx restart

# Create an HTML file with the desired content
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null